import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ClerkProvider } from "@clerk/nextjs";

import "./globals.css";
import TopNavbar from "@/components/section/navbar/top";
import SideBar from "@/components/section/navbar/side";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={inter.className}>
          <SideBar />
          <div className="sm:ml-[72px]">
            <TopNavbar />
            <div className="p-4">{children}</div>
          </div>
        </body>
      </html>
    </ClerkProvider>
  );
}
